(function(){
'use strict';
function boot(){
  if(typeof state==='undefined'||typeof VIEWS==='undefined') return setTimeout(boot,150);
  if(window.__analyticsTabsUpgradeV1) return;window.__analyticsTabsUpgradeV1=true;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const arr=name=>Array.isArray(state[name])?state[name]:[];
  const val=(o,keys,def='')=>{for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];}return def;};
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0;};
  const slug=s=>String(s||'data').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  function style(){if(document.getElementById('analytics-tab-style'))return;const s=document.createElement('style');s.id='analytics-tab-style';s.textContent=`
    .analytics-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.analytics-card{border:1px solid #ddd;border-radius:12px;padding:14px;background:#fff}.analytics-card h3{margin:0 0 10px;font-size:15px}.metric-big{font-size:28px;font-weight:800}.chart-bars{display:grid;gap:8px}.chart-row{display:grid;grid-template-columns:minmax(90px,1.4fr) 3fr auto;gap:8px;align-items:center;font-size:12px}.chart-track{height:12px;background:#eee;border-radius:999px;overflow:hidden}.chart-fill{height:100%;background:currentColor;border-radius:999px;opacity:.75}.chart-line{width:100%;height:150px;overflow:visible}.chart-line polyline{fill:none;stroke:currentColor;stroke-width:3}.chart-line circle{fill:currentColor}.analytics-table-wrap{overflow:auto;max-height:55vh;border:1px solid #ddd;border-radius:10px}.analytics-table{border-collapse:separate;border-spacing:0;width:100%;min-width:760px;font-size:12px}.analytics-table th,.analytics-table td{padding:7px 9px;border-right:1px solid #eee;border-bottom:1px solid #eee;text-align:left;vertical-align:top}.analytics-table th{position:sticky;top:0;background:#f7f7f7;z-index:1}.analytics-tools{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 10px}.analytics-tools input{flex:1;min-width:180px}.analytics-section{margin-top:14px}
  `;document.head.appendChild(s);}
  function countBy(records,get){const m=new Map();for(const r of records){const k=String(get(r)||'Unknown');m.set(k,(m.get(k)||0)+1);}return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
  function sumBy(records,getKey,getValue){const m=new Map();for(const r of records){const k=String(getKey(r)||'Unknown');m.set(k,(m.get(k)||0)+num(getValue(r)));}return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
  function bars(title,rows,suffix=''){const max=Math.max(1,...rows.map(x=>num(x[1])));return `<div class="analytics-card"><h3>${esc(title)}</h3><div class="chart-bars">${rows.slice(0,8).map(([k,v])=>`<div class="chart-row"><span>${esc(k)}</span><div class="chart-track"><div class="chart-fill" style="width:${Math.max(2,num(v)/max*100)}%"></div></div><b>${esc(v)}${esc(suffix)}</b></div>`).join('')||'<p class="muted">No data yet.</p>'}</div></div>`;}
  function line(title,points){if(!points.length)return `<div class="analytics-card"><h3>${esc(title)}</h3><p class="muted">No data yet.</p></div>`;const vals=points.map(p=>num(p[1])),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),w=320,h=120,pad=10;const coords=points.map((p,i)=>[pad+(points.length===1?0:i*(w-2*pad)/(points.length-1)),h-pad-((num(p[1])-min)/span)*(h-2*pad)]);return `<div class="analytics-card"><h3>${esc(title)}</h3><svg class="chart-line" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${coords.map(c=>c.join(',')).join(' ')}"></polyline>${coords.map(c=>`<circle cx="${c[0]}" cy="${c[1]}" r="3"></circle>`).join('')}</svg><small>${esc(points[0][0])} → ${esc(points[points.length-1][0])}</small></div>`;}
  function metric(title,value,sub=''){return `<div class="analytics-card"><h3>${esc(title)}</h3><div class="metric-big">${esc(value)}</div>${sub?`<small>${esc(sub)}</small>`:''}</div>`;}
  function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
  function download(name,cols,records){const rows=[cols.map(c=>c.label),...records.map(r=>cols.map(c=>c.get?c.get(r):val(r,c.keys||[c.key],'')))];const csv=rows.map(x=>x.map(csvCell).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function table(id,title,records,cols){const head=cols.map(c=>`<th>${esc(c.label)}</th>`).join('');const body=records.length?records.map(r=>`<tr>${cols.map(c=>`<td>${esc(c.get?c.get(r):val(r,c.keys||[c.key],''))}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="muted">No records yet.</td></tr>`;return `<div class="card analytics-section"><h2>${esc(title)}</h2><div class="analytics-tools"><input id="${id}Filter" type="search" placeholder="Filter spreadsheet…"><button class="btn ghost" id="${id}Csv" type="button">Download CSV</button><button class="btn ghost" id="${id}Print" type="button">Print</button></div><div class="analytics-table-wrap"><table class="analytics-table" id="${id}Table"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div></div>`;}
  function wire(id,records,cols,file){const q=document.getElementById(id+'Filter'),t=document.getElementById(id+'Table');if(q&&t)q.oninput=()=>{const n=q.value.toLowerCase().trim();t.querySelectorAll('tbody tr').forEach(tr=>tr.style.display=!n||tr.innerText.toLowerCase().includes(n)?'':'none');};document.getElementById(id+'Csv')?.addEventListener('click',()=>download(file,cols,records));document.getElementById(id+'Print')?.addEventListener('click',()=>window.print());}
  function append(html){const target=document.querySelector('#content,#main,main,#app .content,#app');if(target)target.insertAdjacentHTML('beforeend',html);}
  function wrap(route,enhance){if(typeof VIEWS[route]!=='function'||VIEWS[route].__analyticsWrapped)return;const original=VIEWS[route];function wrapped(){const out=original.apply(this,arguments);setTimeout(()=>{try{enhance();}catch(e){console.warn('analytics enhancement failed for '+route,e);}},0);return out;}wrapped.__analyticsWrapped=true;VIEWS[route]=wrapped;}
  const common={
    menus:{state:'menus',cols:[{label:'Menu',keys:['name','title']},{label:'Description',keys:['description']},{label:'Recipes',get:r=>(Array.isArray(r.recipeIds)?r.recipeIds.length:0)},{label:'Updated',keys:['updatedAt','createdAt']}]},
    recipes:{state:'recipes',cols:[{label:'Recipe',keys:['name','title']},{label:'Category',keys:['category','course']},{label:'Yield',keys:['portions','yield']},{label:'Allergens',keys:['allergens']},{label:'Cost',keys:['cost','totalCost']}]},
    stock:{state:'stock',cols:[{label:'Item',keys:['name','item']},{label:'Qty',keys:['qty','quantity']},{label:'Unit',keys:['unit']},{label:'Use by',keys:['useBy']},{label:'Supplier',keys:['supplier']},{label:'Allergens',keys:['allergens']}]},
    deliveries:{state:'deliveries',cols:[{label:'Date',keys:['date','receivedDate']},{label:'Supplier',keys:['supplier']},{label:'Item',keys:['item','product']},{label:'Qty',keys:['qty','quantity']},{label:'Temp °C',keys:['temperature','deliveryTemp']},{label:'Status',keys:['status','accepted']},{label:'Reference',keys:['reference','invoice']}]},
    operations:{state:'operations',cols:[{label:'Task',get:r=>val(r,['title'],val(r.f||{},['title']))},{label:'Status',keys:['status']},{label:'Due',get:r=>val(r,['dueDate'],val(r.f||{},['dueDate']))},{label:'Assigned',get:r=>val(r,['assignedTo'],val(r.f||{},['assignedTo']))},{label:'Notes',keys:['notes']}]},
    paperwork:{state:'paperwork',cols:[{label:'Form / record',keys:['title','name','type']},{label:'Date',keys:['date','createdAt']},{label:'Status',keys:['status']},{label:'Staff',keys:['staff','createdBy','completedBy']},{label:'Notes',keys:['notes','details']}]},
    prep:{state:'prepLists',cols:[{label:'Date',keys:['date']},{label:'Menu',keys:['menuName']},{label:'Covers',keys:['covers']},{label:'Jobs',get:r=>Array.isArray(r.jobs)?r.jobs.length:0},{label:'Completed',get:r=>Array.isArray(r.jobs)?r.jobs.filter(j=>j.completed).length:0},{label:'Created by',keys:['createdBy']}]},
    prepLists:{state:'prepLists',cols:[{label:'Date',keys:['date']},{label:'Menu',keys:['menuName']},{label:'Covers',keys:['covers']},{label:'Jobs',get:r=>Array.isArray(r.jobs)?r.jobs.length:0},{label:'Completed',get:r=>Array.isArray(r.jobs)?r.jobs.filter(j=>j.completed).length:0},{label:'Created by',keys:['createdBy']}]}
  };
  for(const [route,cfg] of Object.entries(common))wrap(route,()=>{const records=arr(cfg.state).slice().reverse();let charts='';if(route==='stock'){const low=records.slice().sort((a,b)=>num(val(a,['qty','quantity']))-num(val(b,['qty','quantity']))).slice(0,8).map(r=>[val(r,['name','item'],'Item'),num(val(r,['qty','quantity']))]);charts=metric('Stock lines',records.length,'Current tracked items')+bars('Lowest stock quantities',low);}else if(route==='recipes'){charts=metric('Recipes',records.length)+bars('Recipes by category',countBy(records,r=>val(r,['category','course'],'Uncategorised')));}else if(route==='menus'){charts=metric('Menus',records.length)+bars('Recipes per menu',records.map(r=>[val(r,['name','title'],'Menu'),Array.isArray(r.recipeIds)?r.recipeIds.length:0]).sort((a,b)=>b[1]-a[1]));}else if(route==='deliveries'){charts=metric('Delivery records',records.length)+bars('Deliveries by status',countBy(records,r=>val(r,['status','accepted'],'Unknown')));}else if(route==='operations'){charts=metric('Operations',records.length)+bars('Tasks by status',countBy(records,r=>val(r,['status'],'Unknown')));}else if(route==='paperwork'){charts=metric('Paperwork records',records.length)+bars('Paperwork by status',countBy(records,r=>val(r,['status'],'Unknown')));}else{const jobs=records.reduce((a,r)=>a+(Array.isArray(r.jobs)?r.jobs.length:0),0),done=records.reduce((a,r)=>a+(Array.isArray(r.jobs)?r.jobs.filter(j=>j.completed).length:0),0);charts=metric('Prep lists',records.length)+metric('Prep completion',jobs?Math.round(done/jobs*100)+'%':'0%',`${done} of ${jobs} jobs`);}append(`<div class="card analytics-section"><h2>Charts & summary</h2><div class="analytics-grid">${charts}</div></div>${table('sheet_'+slug(route),route==='prep'||route==='prepLists'?'Prep spreadsheet':route.charAt(0).toUpperCase()+route.slice(1)+' spreadsheet',records,cfg.cols)}`);wire('sheet_'+slug(route),records,cfg.cols,slug(route)+'.csv');});
  const dedicated={
    waste:()=>{const r=arr('waste');return metric('Waste records',r.length)+metric('Estimated waste cost','£'+r.reduce((a,x)=>a+num(val(x,['estimatedCost','cost'])),0).toFixed(2))+bars('Waste by reason',countBy(r,x=>val(x,['reason','category'],'Unknown')));},
    haccp:()=>{const r=Array.isArray(state.haccpRecords)?state.haccpRecords:arr('haccp');return metric('HACCP checks',r.length)+bars('HACCP results',countBy(r,x=>val(x,['result','status'],'Unknown')));},
    dailychecks:()=>{const r=arr('dailyChecks');return metric('Daily checks',r.length)+bars('Daily check results',countBy(r,x=>val(x,['result','status'],'Unknown')));},
    cleaning:()=>{const r=arr('scheduleCompletions');return metric('Cleaning completions',r.length)+bars('Cleaning results',countBy(r,x=>val(x,['result','status'],'Unknown')));},
    incidents:()=>{const r=Array.isArray(state.incidents)?state.incidents:arr('incidentRecords');return metric('Incidents',r.length)+bars('Incidents by type',countBy(r,x=>val(x,['incidentType','type'],'Unknown')));},
    suppliers:()=>{const r=arr('suppliers');return metric('Suppliers',r.length)+bars('Supplier approval',countBy(r,x=>val(x,['approvalStatus','status'],'Unknown')));},
    traceability:()=>{const r=Array.isArray(state.traceabilityRecords)?state.traceabilityRecords:arr('traceability');return metric('Traceability records',r.length)+bars('Delivery acceptance',countBy(r,x=>val(x,['accepted','status'],'Unknown')));},
    probe:()=>{const r=arr('checks').slice(-30),pts=r.map((x,i)=>[val(x,['date'],String(i+1)),num(val(x,['value','temperature']))]);return metric('Temperature readings',arr('checks').length)+line('Recent temperature trend',pts);},
    pestcontrol:()=>{const r=Array.isArray(state.pestControl)?state.pestControl:arr('pestRecords');return metric('Pest records',r.length)+bars('Pest records by status',countBy(r,x=>val(x,['status'],'Unknown')));},
    labels:()=>{const r=arr('labels');return metric('Labels issued',r.length)+bars('Labels by storage',countBy(r,x=>val(x,['storage'],'Unknown')));}
  };
  for(const [route,getCharts] of Object.entries(dedicated))wrap(route,()=>append(`<div class="card analytics-section"><h2>Charts & summary</h2><div class="analytics-grid">${getCharts()}</div></div>`));
  const staffStores=['clockins','clockIns','timeEntries','timesheets'];const staffStore=()=>staffStores.map(arr).find(x=>x.length)||[];
  for(const route of ['clockin','clocking','staff'])wrap(route,()=>{const r=staffStore();if(!r.length)return;const cols=[{label:'Staff',keys:['staff','name','username']},{label:'Clock in',keys:['clockIn','start','in']},{label:'Clock out',keys:['clockOut','end','out']},{label:'Hours',keys:['hours','duration']},{label:'Date',keys:['date']}];append(`<div class="card analytics-section"><h2>Staff charts & spreadsheet</h2><div class="analytics-grid">${metric('Time records',r.length)}${bars('Records by staff',countBy(r,x=>val(x,['staff','name','username'],'Unknown')))}</div></div>${table('sheet_staff','Staff time spreadsheet',r.slice().reverse(),cols)}`);wire('sheet_staff',r.slice().reverse(),cols,'staff-time.csv');});
  style();
  window.__kitchenAnalytics={countBy,sumBy,bars,line,metric,table};
}
boot();
})();