(function(){
  function boot(){
    if(typeof state==='undefined'||typeof save!=='function'||typeof uid!=='function') return setTimeout(boot,150);
    if(window.__recipeSeedPatch) return;
    window.__recipeSeedPatch=true;
    state.settings=state.settings||{};
    if(state.settings.recipeSeedV1) return;
    state.recipes=Array.isArray(state.recipes)?state.recipes:[];
    const now=new Date().toISOString();
    const I=(name,qty,unit)=>({name,qty,unit});
    const R=(name,course,foodCategory,portions,ingredients,method,allergens,cost,sellingPrice)=>({
      id:uid(),name,course,foodCategory,category:course,portions,ingredients,method,allergens,cost,sellingPrice,
      createdAt:now,createdBy:'Kitchen recipe starter library',seeded:true,needsGeneration:false
    });
    const recipes=[
      R('Chicken Liver Parfait','Starters','Meat',10,[I('Chicken livers',1.2,'kg'),I('Butter',500,'g'),I('Shallots',250,'g'),I('Garlic',20,'g'),I('Brandy',100,'ml'),I('Double cream',250,'ml'),I('Thyme',10,'g'),I('Salt',18,'g')],'1. Trim livers. 2. Sweat shallots, garlic and thyme in butter. 3. Add livers and cook until just pink. 4. Deglaze with brandy. 5. Blend with cream and remaining butter until smooth. 6. Pass, pot and chill rapidly. 7. Serve with toasted bread and chutney.','Milk; gluten if served with toast. VERIFY all packaging.',18,7.95),
      R('Smoked Haddock Fishcake','Starters','Fish',10,[I('Smoked haddock',900,'g'),I('Potatoes',1.5,'kg'),I('Spring onions',120,'g'),I('Parsley',30,'g'),I('Eggs',4,'each'),I('Flour',250,'g'),I('Breadcrumbs',500,'g'),I('Lemon',2,'each')],'1. Poach haddock and flake. 2. Cook and dry potatoes, then mash. 3. Mix fish, potato, spring onion, parsley and seasoning. 4. Shape 10 cakes and chill. 5. Pane in flour, egg and breadcrumbs. 6. Fry until golden and core temperature is safe.','Fish, egg, gluten. VERIFY all packaging.',16,8.5),
      R('Wild Mushroom on Toast','Starters','Vegetarian',10,[I('Mixed mushrooms',1.5,'kg'),I('Sourdough slices',10,'each'),I('Butter',180,'g'),I('Garlic',25,'g'),I('Cream',300,'ml'),I('Parsley',30,'g'),I('Parmesan',150,'g')],'1. Clean and slice mushrooms. 2. Fry hard in batches with butter. 3. Add garlic, cream and parsley; reduce. 4. Toast sourdough. 5. Spoon mushrooms over toast and finish with parmesan.','Milk, gluten. VERIFY cheese suitability and packaging.',19,8.25),
      R('Roast Tomato and Basil Soup','Starters','Vegan',10,[I('Tomatoes',3,'kg'),I('Onions',600,'g'),I('Carrots',400,'g'),I('Garlic',40,'g'),I('Vegetable stock',2,'l'),I('Basil',50,'g'),I('Olive oil',150,'ml')],'1. Roast tomatoes, onions, carrots and garlic with oil. 2. Transfer to pan with stock. 3. Simmer 25 minutes. 4. Blend smooth. 5. Add basil, season and chill or hold safely.','No declared allergens in core recipe; VERIFY stock and packaging.',12,6.95),
      R('Steak and Ale Pie','Mains','Meat',10,[I('Diced beef',2.2,'kg'),I('Onions',600,'g'),I('Carrots',500,'g'),I('Mushrooms',500,'g'),I('Ale',750,'ml'),I('Beef stock',1.5,'l'),I('Flour',180,'g'),I('Puff pastry',1.2,'kg'),I('Egg',2,'each')],'1. Brown beef in batches. 2. Sweat vegetables. 3. Add flour, ale and stock. 4. Return beef and braise until tender. 5. Cool filling quickly. 6. Portion into dishes, top with pastry and egg wash. 7. Bake until golden and piping hot.','Gluten, egg; possible celery in stock. VERIFY ale, stock and pastry.',32,15.95),
      R('Pan-Roasted Chicken Supreme','Mains','Meat',10,[I('Chicken supremes',10,'each'),I('Butter',180,'g'),I('Garlic',30,'g'),I('Thyme',20,'g'),I('Chicken stock',1.2,'l'),I('White wine',300,'ml'),I('Double cream',500,'ml')],'1. Season chicken. 2. Sear skin-side down until golden. 3. Turn, add garlic and thyme, then roast until safely cooked. 4. Rest chicken. 5. Deglaze pan with wine, add stock and reduce. 6. Add cream and finish with butter.','Milk; possible celery/sulphites in stock and wine. VERIFY packaging.',29,16.5),
      R('Beer-Battered Haddock and Chips','Mains','Fish',10,[I('Haddock fillets',10,'each'),I('Flour',1,'kg'),I('Beer',1.2,'l'),I('Baking powder',30,'g'),I('Potatoes',4,'kg'),I('Peas',1.5,'kg'),I('Butter',120,'g')],'1. Cut and blanch chips, cool, then fry to order. 2. Mix flour, baking powder and cold beer into batter. 3. Dust fish in flour, batter and fry until crisp and safely cooked. 4. Cook peas and crush with butter. 5. Drain and serve immediately.','Fish, gluten, milk; possible sulphites. VERIFY beer and flour.',31,16.95),
      R('Salmon with Lemon Butter Sauce','Mains','Fish',10,[I('Salmon portions',10,'each'),I('Butter',300,'g'),I('Lemons',4,'each'),I('White wine',300,'ml'),I('Fish stock',800,'ml'),I('Parsley',30,'g')],'1. Season and pan-sear salmon. 2. Finish in oven until safely cooked. 3. Reduce wine and fish stock. 4. Whisk in cold butter. 5. Add lemon and parsley. 6. Serve sauce immediately.','Fish, milk; possible sulphites and celery. VERIFY stock and wine.',36,18.5),
      R('Mushroom and Spinach Wellington','Mains','Vegetarian',10,[I('Puff pastry',1.4,'kg'),I('Mushrooms',2,'kg'),I('Spinach',900,'g'),I('Onions',500,'g'),I('Garlic',30,'g'),I('Cream cheese',500,'g'),I('Egg',2,'each')],'1. Cook mushrooms, onions and garlic until dry. 2. Wilt spinach and squeeze dry. 3. Mix with cream cheese and cool. 4. Wrap portions in pastry. 5. Egg wash, chill and bake until crisp and piping hot.','Gluten, milk, egg. VERIFY pastry and cheese suitability.',25,14.95),
      R('Chickpea and Sweet Potato Curry','Mains','Vegan',10,[I('Chickpeas',2,'kg'),I('Sweet potatoes',2,'kg'),I('Onions',700,'g'),I('Tomatoes',1.5,'kg'),I('Coconut milk',1.2,'l'),I('Garlic',40,'g'),I('Ginger',50,'g'),I('Curry spices',80,'g')],'1. Sweat onions, garlic and ginger. 2. Add spices and cook out. 3. Add sweet potato, tomatoes and coconut milk. 4. Simmer until tender. 5. Add chickpeas and reduce to coating consistency. 6. Season and finish with herbs.','No declared allergens in core recipe; VERIFY spice mix and coconut product.',18,13.5),
      R('Sticky Toffee Pudding','Desserts','Dessert',10,[I('Dates',500,'g'),I('Boiling water',600,'ml'),I('Bicarbonate of soda',12,'g'),I('Butter',300,'g'),I('Brown sugar',450,'g'),I('Eggs',6,'each'),I('Flour',500,'g'),I('Double cream',700,'ml')],'1. Soak dates with bicarbonate and blend. 2. Cream butter and sugar. 3. Add eggs, flour and date mixture. 4. Bake in lined tray. 5. Make sauce with cream, butter and sugar. 6. Portion and reheat with sauce.','Milk, egg, gluten. VERIFY all packaging.',14,7.5),
      R('Apple and Blackberry Crumble','Desserts','Dessert',10,[I('Cooking apples',2.5,'kg'),I('Blackberries',800,'g'),I('Sugar',450,'g'),I('Flour',700,'g'),I('Butter',450,'g'),I('Oats',250,'g'),I('Cinnamon',10,'g')],'1. Peel and slice apples. 2. Cook briefly with sugar and cinnamon. 3. Fold in blackberries and tray up. 4. Rub flour, butter, oats and sugar to crumble. 5. Top fruit and bake until bubbling and golden.','Milk, gluten; oats may contain gluten. VERIFY packaging.',13,7.25),
      R('Triple Chocolate Brownie','Desserts','Dessert',10,[I('Dark chocolate',500,'g'),I('Butter',350,'g'),I('Sugar',550,'g'),I('Eggs',6,'each'),I('Flour',250,'g'),I('Cocoa powder',80,'g'),I('White chocolate',180,'g'),I('Milk chocolate',180,'g')],'1. Melt dark chocolate and butter. 2. Whisk eggs and sugar. 3. Fold in chocolate mixture, flour and cocoa. 4. Add chocolate pieces. 5. Bake until just set, cool and portion.','Milk, egg, gluten, soya may be present. VERIFY chocolate packaging.',16,7.75),
      R('Herb Roasted New Potatoes','Sides','Vegan',10,[I('New potatoes',2.5,'kg'),I('Olive oil',180,'ml'),I('Garlic',30,'g'),I('Rosemary',20,'g'),I('Thyme',20,'g'),I('Salt',20,'g')],'1. Wash and halve potatoes. 2. Blanch until nearly tender and steam dry. 3. Toss with oil, garlic, herbs and salt. 4. Roast until crisp and hot throughout.','No declared allergens in core recipe; VERIFY oil and seasoning.',7,4.25),
      R('Cauliflower Cheese','Sides','Vegetarian',10,[I('Cauliflower',2.5,'kg'),I('Milk',1.5,'l'),I('Butter',160,'g'),I('Flour',160,'g'),I('Cheddar',500,'g'),I('Mustard',50,'g')],'1. Blanch cauliflower and drain well. 2. Make roux with butter and flour. 3. Gradually add milk and cook out. 4. Add mustard and most cheese. 5. Coat cauliflower, top with remaining cheese and bake until golden.','Milk, gluten, mustard. VERIFY all packaging.',12,5.25),
      R('Red Wine Jus','Sauces','Other',20,[I('Beef stock',2,'l'),I('Red wine',750,'ml'),I('Shallots',300,'g'),I('Carrots',250,'g'),I('Celery',200,'g'),I('Tomato puree',80,'g'),I('Butter',120,'g')],'1. Caramelise vegetables. 2. Add tomato puree and cook out. 3. Deglaze with wine and reduce by two thirds. 4. Add stock and simmer until glossy. 5. Pass, reduce to consistency and mount with butter.','Milk, celery, sulphites. VERIFY stock and wine.',11,1.5),
      R('Tartare Sauce','Sauces','Other',20,[I('Mayonnaise',1,'kg'),I('Gherkins',180,'g'),I('Capers',100,'g'),I('Parsley',25,'g'),I('Lemon juice',80,'ml'),I('Dijon mustard',35,'g')],'1. Finely chop gherkins, capers and parsley. 2. Fold through mayonnaise. 3. Add lemon and mustard. 4. Season, label and refrigerate.','Egg, mustard; possible sulphites. VERIFY mayonnaise and pickles.',8,0.75)
    ];
    const existing=new Set(state.recipes.map(r=>String(r.name||'').trim().toLowerCase()));
    let added=0;
    for(const r of recipes){ if(!existing.has(r.name.toLowerCase())){ state.recipes.push(r); added++; } }
    state.settings.recipeSeedV1=true;
    state.settings.recipeSeedCount=added;
    if(typeof audit==='function') audit('seed','recipe',{added,library:'starter recipe library'});
    save();
    if(typeof render==='function') render();
    if(typeof toast==='function'&&added) toast(added+' recipes added across all sections','ok');
  }
  boot();
})();
