(function(){
'use strict';
function boot(){
  if(typeof state==='undefined'||typeof VIEWS==='undefined'||typeof page!=='function'||typeof save!=='function') return setTimeout(boot,120);
  if(window.__tabSpreadsheetUpgradeV1) return;
  window.__tabSpreadsheetUpgradeV1=true;

  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>`rec_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const today=()=>new Date().toISOString().slice(0,10);
  const now=()=>new Date().toISOString();
  const who=()=>{try{return me?.name||me?.username||'';}catch(_){return'';}};
  const isManager=()=>{try{return String(me?.role||'').toLowerCase()==='manager';}catch(_){return false;}};
  const arr=(name)=>{state[name]=Array.isArray(state[name])?state[name]:[];return state[name];};
  const value=(r,keys,def='')=>{for(const k of keys){if(r&&r[k]!==undefined&&r[k]!==null&&r[k]!=='')return r[k];}return def;};
  const persist=async(msg)=>{await Promise.resolve(save());if(typeof toast==='function')toast(msg,'ok');};
  const bad=msg=>{if(typeof toast==='function')toast(msg,'bad');};

  function styles(){
    if(document.getElementById('solid-tab-sheet-style'))return;
    const s=document.createElement('style');s.id='solid-tab-sheet-style';s.textContent=`
      .sheet-wrap{overflow:auto;border:1px solid #d8d8d8;border-radius:10px;background:#fff;max-height:58vh}
      .sheet{border-collapse:separate;border-spacing:0;width:100%;min-width:860px;font-size:13px}
      .sheet th,.sheet td{padding:8px 10px;border-right:1px solid #ececec;border-bottom:1px solid #ececec;text-align:left;vertical-align:top;white-space:normal}
      .sheet th{position:sticky;top:0;z-index:2;background:#f7f7f7;font-size:12px;text-transform:uppercase;letter-spacing:.02em}
      .sheet tr:last-child td{border-bottom:0}.sheet th:last-child,.sheet td:last-child{border-right:0}
      .sheet td.num{text-align:right;font-variant-numeric:tabular-nums}.sheet .muted-cell{color:#777}
      .sheet-tools{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 10px}.sheet-tools input{min-width:220px;flex:1}
      .sheet-empty{padding:24px;text-align:center;color:#777}.status-chip{display:inline-block;padding:2px 7px;border-radius:999px;background:#eee;font-size:11px;font-weight:700}
      .solid-form-help{font-size:12px;color:#666;margin:-4px 0 8px}.danger-note{border-left:4px solid #b23b3b;padding-left:10px}
    `;document.head.appendChild(s);
  }

  function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
  function downloadCsv(filename,columns,records){
    const rows=[columns.map(c=>c.label),...records.map(r=>columns.map(c=>typeof c.get==='function'?c.get(r):value(r,c.keys||[c.key],'')))];
    const csv=rows.map(row=>row.map(csvCell).join(',')).join('\n');
    const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200);
  }

  function sheet(id,columns,records,filename){
    const head=columns.map(c=>`<th>${esc(c.label)}</th>`).join('');
    const body=records.length?records.map(r=>`<tr>${columns.map(c=>{const raw=typeof c.get==='function'?c.get(r):value(r,c.keys||[c.key],'');const txt=raw===true?'Yes':raw===false?'No':raw;return `<td class="${c.num?'num':''}">${esc(txt)}</td>`;}).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}" class="sheet-empty">No records yet.</td></tr>`;
    return `<div class="sheet-tools"><input id="${id}Search" type="search" placeholder="Filter this spreadsheet…"><button class="btn ghost" id="${id}Csv" type="button">Download CSV</button><button class="btn ghost" id="${id}Print" type="button">Print</button></div><div class="sheet-wrap"><table class="sheet" id="${id}Table"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;
  }
  function wireSheet(id,columns,records,filename){
    const q=document.getElementById(id+'Search'),table=document.getElementById(id+'Table');
    if(q&&table)q.oninput=()=>{const needle=q.value.trim().toLowerCase();table.querySelectorAll('tbody tr').forEach(tr=>{tr.style.display=!needle||tr.innerText.toLowerCase().includes(needle)?'':'none';});};
    document.getElementById(id+'Csv')?.addEventListener('click',()=>downloadCsv(filename,columns,records));
    document.getElementById(id+'Print')?.addEventListener('click',()=>window.print());
  }

  function pestRecords(){if(Array.isArray(state.pestControl))return state.pestControl;if(Array.isArray(state.pestRecords))return state.pestRecords;state.pestControl=[];return state.pestControl;}
  function haccpRecords(){if(Array.isArray(state.haccpRecords))return state.haccpRecords;if(Array.isArray(state.haccp))return state.haccp;state.haccpRecords=[];return state.haccpRecords;}
  function traceRecords(){if(Array.isArray(state.traceabilityRecords))return state.traceabilityRecords;if(Array.isArray(state.traceability))return state.traceability;state.traceabilityRecords=[];return state.traceabilityRecords;}
  function incidentRecords(){if(Array.isArray(state.incidents))return state.incidents;if(Array.isArray(state.incidentRecords))return state.incidentRecords;state.incidents=[];return state.incidents;}

  function pestView(){
    const records=pestRecords().slice().reverse();
    const cols=[{label:'Date',keys:['date']},{label:'Time',keys:['timeLocal','time']},{label:'Area',keys:['area']},{label:'Pest / evidence',keys:['pestType','type']},{label:'Exact evidence',keys:['evidence','details']},{label:'Immediate action',keys:['action','correctiveAction']},{label:'Reference',keys:['reference']},{label:'Follow-up',keys:['followUp']},{label:'Status',keys:['status']},{label:'Recorded by',keys:['recordedBy','createdBy']}];
    page('Pest control','Operational pest-control log with a proper record form and spreadsheet history.',`<div class="grid cols-even"><div class="card"><h2>Record pest activity</h2><form id="solidPestForm" class="form two"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Time<input name="timeLocal" type="time" required></label><label>Area<select name="area" required><option>Kitchen</option><option>Dry store</option><option>Cold room</option><option>Cellar</option><option>Waste area</option><option>Delivery area</option><option>Dining / bar</option><option>External perimeter</option></select></label><label>Pest / evidence<select name="pestType" required><option>Rodent</option><option>Flying insect</option><option>Crawling insect</option><option>Bird</option><option>Droppings / gnawing</option><option>Damaged packaging</option><option>Other evidence</option></select></label><label class="full">Exact location and evidence<textarea name="evidence" required></textarea></label><label class="full">Immediate corrective action<textarea name="action" required></textarea></label><label>Trap / bait / contractor reference<input name="reference"></label><label>Follow-up date<input name="followUp" type="date"></label><label>Status<select name="status"><option>Open</option><option>Monitoring</option><option>Contractor notified</option><option>Closed</option></select></label><label>Recorded by<input name="recordedBy" value="${esc(who())}" required></label><button class="btn full" type="submit">Save pest-control record</button></form></div><div class="card"><h2>What belongs here</h2><p>Every sighting or sign should have a location, evidence, immediate action and follow-up status. Do not use this tab as a general notes page.</p></div></div><div class="card mt"><h2>Pest-control spreadsheet</h2>${sheet('pestSheet',cols,records,'pest-control.csv')}</div>`);
    document.getElementById('solidPestForm').onsubmit=async e=>{e.preventDefault();pestRecords().push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Pest-control record saved');pestView();};wireSheet('pestSheet',cols,records,'pest-control.csv');
  }

  function haccpView(){
    const records=haccpRecords().slice().reverse();
    const cols=[{label:'Date',keys:['date']},{label:'Process / dish',keys:['process','dish']},{label:'Hazard',keys:['hazard']},{label:'CCP / control',keys:['ccp','control']},{label:'Critical limit',keys:['criticalLimit','limit']},{label:'Monitoring result',keys:['monitoringResult','resultValue']},{label:'Result',keys:['result','status']},{label:'Corrective action',keys:['correctiveAction','action']},{label:'Verified by',keys:['verifiedBy']},{label:'Recorded by',keys:['recordedBy','createdBy']}];
    page('HACCP','Critical-control monitoring with pass/fail evidence and corrective action.',`<div class="grid cols-even"><div class="card"><h2>Record HACCP check</h2><form id="solidHaccpForm" class="form two"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Process / dish<input name="process" required placeholder="e.g. cooling gravy"></label><label class="full">Hazard<input name="hazard" required placeholder="Biological, chemical, physical or allergen hazard"></label><label>CCP / control point<input name="ccp" required></label><label>Critical limit<input name="criticalLimit" required placeholder="e.g. ≤5°C within 4 hours"></label><label class="full">Monitoring result<input name="monitoringResult" required placeholder="Actual time, temperature or observation"></label><label>Result<select name="result"><option>Pass</option><option>Fail</option></select></label><label>Recorded by<input name="recordedBy" value="${esc(who())}" required></label><label class="full">Corrective action<textarea name="correctiveAction" placeholder="Required for a failed check"></textarea></label><label>Verified by<input name="verifiedBy"></label><button class="btn full" type="submit">Save HACCP record</button></form></div><div class="card"><h2>Rule</h2><p class="danger-note">A failed critical-control check must have a corrective action before it can be saved.</p></div></div><div class="card mt"><h2>HACCP spreadsheet</h2>${sheet('haccpSheet',cols,records,'haccp-log.csv')}</div>`);
    document.getElementById('solidHaccpForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.result==='Fail'&&!String(f.correctiveAction||'').trim())return bad('Enter corrective action for a failed HACCP check');haccpRecords().push({id:uid(),...f,createdAt:now(),createdBy:who()});await persist('HACCP record saved');haccpView();};wireSheet('haccpSheet',cols,records,'haccp-log.csv');
  }

  function cleaningView(){
    const schedules=arr('cleaningSchedules').slice().reverse(),done=arr('scheduleCompletions').slice().reverse();
    const scheduleCols=[{label:'Area / item',keys:['area','item','task']},{label:'Task',keys:['task','method']},{label:'Frequency',keys:['frequency']},{label:'Chemical / method',keys:['chemical','method']},{label:'Responsible',keys:['responsible','assignedTo']},{label:'Next due',keys:['nextDue','dueDate']},{label:'Notes',keys:['notes']}];
    const completeCols=[{label:'Date',keys:['date']},{label:'Area / item',keys:['area','item','task']},{label:'Task',keys:['task']},{label:'Completed by',keys:['completedBy','staff','createdBy']},{label:'Result',keys:['result','status']},{label:'Corrective action',keys:['correctiveAction','notes']},{label:'Time',keys:['timeLocal','time']}];
    const scheduleOptions=arr('cleaningSchedules').map(x=>`<option value="${esc(x.id)}">${esc(value(x,['area','item','task'],'Cleaning task'))} — ${esc(value(x,['task','method'],''))}</option>`).join('');
    page('Cleaning','Cleaning schedule plus completion records. These are separate spreadsheets because they serve different purposes.',`<div class="grid cols-even"><div class="card"><h2>Add cleaning schedule item</h2><form id="solidCleanScheduleForm" class="form two"><label>Area / equipment<input name="area" required></label><label>Task<input name="task" required></label><label>Frequency<select name="frequency"><option>Each service</option><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>As required</option></select></label><label>Responsible<input name="responsible" required></label><label class="full">Chemical / method<input name="chemical" placeholder="Product, dilution and method"></label><label>Next due<input name="nextDue" type="date"></label><label>Notes<input name="notes"></label><button class="btn full" type="submit">Add schedule item</button></form></div><div class="card"><h2>Record cleaning completion</h2><form id="solidCleanCompleteForm" class="form two"><label class="full">Scheduled task<select name="scheduleId"><option value="">Ad-hoc cleaning</option>${scheduleOptions}</select></label><label>Area / equipment<input name="area" required></label><label>Task<input name="task" required></label><label>Date<input name="date" type="date" value="${today()}" required></label><label>Time<input name="timeLocal" type="time"></label><label>Completed by<input name="completedBy" value="${esc(who())}" required></label><label>Result<select name="result"><option>Satisfactory</option><option>Re-clean required</option><option>Maintenance required</option></select></label><label class="full">Corrective action / notes<textarea name="correctiveAction"></textarea></label><button class="btn full" type="submit">Save completion</button></form></div></div><div class="card mt"><h2>Cleaning schedule spreadsheet</h2>${sheet('cleanScheduleSheet',scheduleCols,schedules,'cleaning-schedule.csv')}</div><div class="card mt"><h2>Cleaning completion spreadsheet</h2>${sheet('cleanDoneSheet',completeCols,done,'cleaning-completions.csv')}</div>`);
    document.getElementById('solidCleanScheduleForm').onsubmit=async e=>{e.preventDefault();arr('cleaningSchedules').push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Cleaning schedule item saved');cleaningView();};
    document.getElementById('solidCleanCompleteForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.scheduleId){const s=arr('cleaningSchedules').find(x=>String(x.id)===String(f.scheduleId));if(s){f.area=f.area||s.area||s.item||'';f.task=f.task||s.task||'';}}arr('scheduleCompletions').push({id:uid(),...f,createdAt:now(),createdBy:who()});await persist('Cleaning completion saved');cleaningView();};
    wireSheet('cleanScheduleSheet',scheduleCols,schedules,'cleaning-schedule.csv');wireSheet('cleanDoneSheet',completeCols,done,'cleaning-completions.csv');
  }

  function dailyChecksView(){
    const records=arr('dailyChecks').slice().reverse();
    const cols=[{label:'Date',keys:['date']},{label:'Period',keys:['period']},{label:'Opening / closing check',keys:['check','item','title']},{label:'Result',keys:['result','status']},{label:'Issue found',keys:['issue','notes']},{label:'Corrective action',keys:['correctiveAction','action']},{label:'Completed by',keys:['completedBy','staff','createdBy']},{label:'Verified by',keys:['verifiedBy']}];
    page('Daily checks','Opening, service and closing checks in one auditable spreadsheet.',`<div class="grid cols-even"><div class="card"><h2>Record daily check</h2><form id="solidDailyForm" class="form two"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Period<select name="period"><option>Opening</option><option>Pre-service</option><option>Mid-service</option><option>Closing</option></select></label><label class="full">Check<input name="check" required placeholder="e.g. handwash station stocked"></label><label>Result<select name="result"><option>Pass</option><option>Fail</option><option>N/A</option></select></label><label>Completed by<input name="completedBy" value="${esc(who())}" required></label><label class="full">Issue found<textarea name="issue"></textarea></label><label class="full">Corrective action<textarea name="correctiveAction"></textarea></label><label>Verified by<input name="verifiedBy"></label><button class="btn full" type="submit">Save daily check</button></form></div><div class="card"><h2>Examples</h2><p>Opening checks, date labels, handwash supplies, fridge/freezer status, cleaning readiness, allergen controls, closing shutdown and waste/security checks.</p></div></div><div class="card mt"><h2>Daily-check spreadsheet</h2>${sheet('dailySheet',cols,records,'daily-checks.csv')}</div>`);
    document.getElementById('solidDailyForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.result==='Fail'&&!String(f.correctiveAction||'').trim())return bad('Enter corrective action for a failed check');arr('dailyChecks').push({id:uid(),...f,createdAt:now(),createdBy:who()});await persist('Daily check saved');dailyChecksView();};wireSheet('dailySheet',cols,records,'daily-checks.csv');
  }

  function wasteView(){
    const records=arr('waste').slice().reverse();
    const cols=[{label:'Date',keys:['date']},{label:'Item',keys:['item','food']},{label:'Category',keys:['category']},{label:'Qty',keys:['quantity','qty'],num:true},{label:'Unit',keys:['unit']},{label:'Reason',keys:['reason']},{label:'Estimated cost',keys:['cost','estimatedCost'],num:true},{label:'Action / prevention',keys:['prevention','action','notes']},{label:'Recorded by',keys:['recordedBy','createdBy']}];
    page('Waste','Food-waste recording with quantity, reason, cost and prevention tracking.',`<div class="grid cols-even"><div class="card"><h2>Record waste</h2><form id="solidWasteForm" class="form two"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Food / item<input name="item" required></label><label>Category<select name="category"><option>Prep trim</option><option>Over-production</option><option>Spoilage</option><option>Expired / use-by</option><option>Returned plate</option><option>Damaged delivery</option><option>Other</option></select></label><label>Reason<input name="reason" required></label><label>Quantity<input name="quantity" type="number" min="0" step="0.01" required></label><label>Unit<select name="unit"><option>kg</option><option>g</option><option>litres</option><option>ml</option><option>portions</option><option>units</option></select></label><label>Estimated cost £<input name="estimatedCost" type="number" min="0" step="0.01"></label><label>Recorded by<input name="recordedBy" value="${esc(who())}" required></label><label class="full">Prevention / action<textarea name="prevention" placeholder="How to reduce repeat waste"></textarea></label><button class="btn full" type="submit">Save waste record</button></form></div><div class="card"><h2>Purpose</h2><p>This is an operational waste log, not just a note. Quantity, reason and cost let you identify recurring losses.</p></div></div><div class="card mt"><h2>Waste spreadsheet</h2>${sheet('wasteSheet',cols,records,'waste-log.csv')}</div>`);
    document.getElementById('solidWasteForm').onsubmit=async e=>{e.preventDefault();arr('waste').push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Waste record saved');wasteView();};wireSheet('wasteSheet',cols,records,'waste-log.csv');
  }

  function traceabilityView(){
    const records=traceRecords().slice().reverse();
    const cols=[{label:'Date received',keys:['date','receivedDate']},{label:'Supplier',keys:['supplier']},{label:'Product',keys:['product','item']},{label:'Batch / lot',keys:['batch','lot']},{label:'Use-by / best-before',keys:['useBy','bestBefore']},{label:'Qty',keys:['quantity','qty'],num:true},{label:'Unit',keys:['unit']},{label:'Delivery temp °C',keys:['temperature','deliveryTemp'],num:true},{label:'Invoice / delivery note',keys:['reference','invoice']},{label:'Accepted?',keys:['accepted']},{label:'Recorded by',keys:['recordedBy','createdBy']}];
    const supplierOptions=arr('suppliers').map(s=>`<option>${esc(value(s,['name','supplierName'],''))}</option>`).join('');
    page('Traceability','Supplier-to-product traceability with batch, date and delivery evidence.',`<div class="grid cols-even"><div class="card"><h2>Record traceability item</h2><form id="solidTraceForm" class="form two"><label>Date received<input name="receivedDate" type="date" value="${today()}" required></label><label>Supplier<input name="supplier" list="solidSupplierList" required><datalist id="solidSupplierList">${supplierOptions}</datalist></label><label>Product<input name="product" required></label><label>Batch / lot<input name="batch" required></label><label>Use-by / best-before<input name="useBy" type="date"></label><label>Quantity<input name="quantity" type="number" min="0" step="0.01"></label><label>Unit<input name="unit"></label><label>Delivery temp °C<input name="deliveryTemp" type="number" step="0.1"></label><label>Invoice / delivery-note ref<input name="reference"></label><label>Accepted?<select name="accepted"><option>Yes</option><option>No</option><option>Quarantined</option></select></label><label class="full">Condition / notes<textarea name="notes"></textarea></label><label>Recorded by<input name="recordedBy" value="${esc(who())}" required></label><button class="btn full" type="submit">Save traceability record</button></form></div><div class="card"><h2>Minimum traceability</h2><p>Supplier, product and batch/lot should be recorded for anything that may need to be traced or recalled.</p></div></div><div class="card mt"><h2>Traceability spreadsheet</h2>${sheet('traceSheet',cols,records,'traceability.csv')}</div>`);
    document.getElementById('solidTraceForm').onsubmit=async e=>{e.preventDefault();traceRecords().push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Traceability record saved');traceabilityView();};wireSheet('traceSheet',cols,records,'traceability.csv');
  }

  function incidentsView(){
    const records=incidentRecords().slice().reverse();
    const cols=[{label:'Date',keys:['date']},{label:'Time',keys:['timeLocal','time']},{label:'Type',keys:['type','incidentType']},{label:'Area',keys:['area']},{label:'Person(s)',keys:['person','people']},{label:'What happened',keys:['details','description']},{label:'Immediate action',keys:['action','immediateAction']},{label:'Escalated to',keys:['escalatedTo']},{label:'Follow-up',keys:['followUp']},{label:'Status',keys:['status']},{label:'Recorded by',keys:['recordedBy','createdBy']}];
    page('Incidents','Food-safety, injury, allergen and operational incident recording.',`<div class="grid cols-even"><div class="card"><h2>Record incident</h2><form id="solidIncidentForm" class="form two"><label>Date<input name="date" type="date" value="${today()}" required></label><label>Time<input name="timeLocal" type="time" required></label><label>Incident type<select name="incidentType"><option>Food safety</option><option>Allergen</option><option>Injury / accident</option><option>Equipment failure</option><option>Power / refrigeration failure</option><option>Customer complaint</option><option>Contamination / foreign body</option><option>Other</option></select></label><label>Area<input name="area" required></label><label class="full">Person(s) involved<input name="person"></label><label class="full">What happened<textarea name="description" required></textarea></label><label class="full">Immediate action<textarea name="immediateAction" required></textarea></label><label>Escalated to<input name="escalatedTo"></label><label>Follow-up date<input name="followUp" type="date"></label><label>Status<select name="status"><option>Open</option><option>Under review</option><option>Closed</option></select></label><label>Recorded by<input name="recordedBy" value="${esc(who())}" required></label><button class="btn full" type="submit">Save incident</button></form></div><div class="card"><h2>Important</h2><p class="danger-note">This record does not replace any legal accident-reporting, emergency or food-safety notification duty that may apply.</p></div></div><div class="card mt"><h2>Incident spreadsheet</h2>${sheet('incidentSheet',cols,records,'incidents.csv')}</div>`);
    document.getElementById('solidIncidentForm').onsubmit=async e=>{e.preventDefault();incidentRecords().push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Incident saved');incidentsView();};wireSheet('incidentSheet',cols,records,'incidents.csv');
  }

  function suppliersView(){
    const records=arr('suppliers').slice().sort((a,b)=>String(value(a,['name','supplierName'],'')).localeCompare(String(value(b,['name','supplierName'],''))));
    const cols=[{label:'Supplier',keys:['name','supplierName']},{label:'Category',keys:['category']},{label:'Contact',keys:['contact']},{label:'Phone',keys:['phone']},{label:'Email',keys:['email']},{label:'Account / ref',keys:['accountRef','reference']},{label:'Approval status',keys:['status','approvalStatus']},{label:'Last review',keys:['lastReview']},{label:'Next review',keys:['nextReview']},{label:'Notes',keys:['notes']}];
    page('Suppliers','Approved-supplier register with contact and review information.',`<div class="grid cols-even"><div class="card"><h2>Add supplier</h2><form id="solidSupplierForm" class="form two"><label>Supplier name<input name="name" required></label><label>Category<input name="category" placeholder="Meat, fish, produce, dry goods…"></label><label>Contact name<input name="contact"></label><label>Phone<input name="phone" type="tel"></label><label>Email<input name="email" type="email"></label><label>Account / reference<input name="accountRef"></label><label>Approval status<select name="approvalStatus"><option>Approved</option><option>Provisional</option><option>On hold</option><option>Do not use</option></select></label><label>Last review<input name="lastReview" type="date"></label><label>Next review<input name="nextReview" type="date"></label><label class="full">Notes / conditions<textarea name="notes"></textarea></label><button class="btn full" type="submit">Save supplier</button></form></div><div class="card"><h2>Supplier register</h2><p>Keep approval status and review dates here. Delivery-specific temperatures, batch numbers and acceptance belong in Traceability / Deliveries.</p></div></div><div class="card mt"><h2>Supplier spreadsheet</h2>${sheet('supplierSheet',cols,records,'suppliers.csv')}</div>`);
    document.getElementById('solidSupplierForm').onsubmit=async e=>{e.preventDefault();arr('suppliers').push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Supplier saved');suppliersView();};wireSheet('supplierSheet',cols,records,'suppliers.csv');
  }

  function probeView(){
    const records=arr('checks').slice().reverse();
    const appliances=arr('appliances');
    const opts=appliances.map(a=>`<option value="${esc(a.id)}">${esc(a.name||a.label||'Appliance')}</option>`).join('');
    const cols=[{label:'Date',keys:['date']},{label:'Time',get:r=>value(r,['time','timeLocal'])},{label:'Unit',get:r=>{const a=appliances.find(x=>String(x.id)===String(r.applianceId));return a?.name||r.applianceName||r.applianceId||'';}},{label:'Period',keys:['period']},{label:'Reading °C',keys:['value','temperature'],num:true},{label:'Status',keys:['status']},{label:'Method',keys:['method']},{label:'Corrective action / notes',keys:['notes','correctiveAction']},{label:'Staff',keys:['staff','recordedBy','createdBy']}];
    page('Probe & sensors','Temperature/probe entry with the readings shown as a spreadsheet log.',`<div class="grid cols-even"><div class="card"><h2>Record probe reading</h2><form id="solidProbeForm" class="form two"><label class="full">Unit / appliance<select name="applianceId" required><option value="">Select unit</option>${opts}</select></label><label>Reading °C<input name="value" type="number" step="0.1" required></label><label>Period<select name="period"><option>AM</option><option>PM</option><option>Spot check</option></select></label><label>Method<select name="method"><option>Bluetooth probe</option><option>Manual probe</option><option>Display reading</option></select></label><label class="full">Corrective action / notes<textarea name="notes"></textarea></label><button class="btn full" type="submit">Save reading</button></form><div class="btn-row mt"><button class="btn ghost" id="solidProbeConnect" type="button">Connect Bluetooth probe</button></div></div><div class="card"><h2>Rule</h2><p>Out-of-range readings require corrective-action notes. Appliance targets remain configured in Settings.</p></div></div><div class="card mt"><h2>Temperature spreadsheet</h2>${sheet('probeSheet',cols,records,'temperature-readings.csv')}</div>`);
    document.getElementById('solidProbeForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),a=appliances.find(x=>String(x.id)===String(f.applianceId));if(!a)return bad('Select a unit');const v=Number(f.value);let status='ok';if(typeof statusTemp==='function')status=statusTemp(v,a);else if(Number.isFinite(Number(a.critical))&&v>=Number(a.critical))status='bad';else if(Number.isFinite(Number(a.target))&&v>Number(a.target))status='warn';if(status!=='ok'&&!String(f.notes||'').trim())return bad('Enter corrective action for an out-of-range reading');arr('checks').push({id:uid(),date:today(),time:now(),applianceId:a.id,period:f.period,value:v,status,method:f.method,notes:String(f.notes||'').trim(),staff:who()});await persist(`${a.name||'Reading'} saved`);probeView();};
    document.getElementById('solidProbeConnect').onclick=()=>{for(const n of['connectProbe','connectBluetoothProbe','startProbe','startBluetoothProbe'])if(typeof window[n]==='function')return window[n]();if(typeof toast==='function')toast('Bluetooth probe connection is not available on this device; enter the reading manually.','warn');};wireSheet('probeSheet',cols,records,'temperature-readings.csv');
  }

  function labelsView(){
    const records=arr('labels').slice().reverse();
    const cols=[{label:'Prepared',keys:['prepDate']},{label:'Use by',keys:['useBy']},{label:'Food / preparation',keys:['itemName','name']},{label:'Qty',keys:['quantity','qty'],num:true},{label:'Unit',keys:['unit']},{label:'Storage',keys:['storage']},{label:'Allergens',keys:['allergens']},{label:'Batch / notes',keys:['batch','notes']},{label:'Prepared by',keys:['preparedBy','createdBy']}];
    page('Labels','Food-label creation plus a spreadsheet register of labels issued.',`<div class="grid cols-even"><div class="card"><h2>Create food label</h2><form id="solidLabelForm" class="form two"><label class="full">Food / preparation<input name="itemName" required></label><label>Prepared date<input name="prepDate" type="date" value="${today()}" required></label><label>Use-by date<input name="useBy" type="date" required></label><label>Quantity<input name="quantity" type="number" min="0" step="0.01"></label><label>Unit<select name="unit"><option>kg</option><option>g</option><option>litres</option><option>ml</option><option>portions</option><option>units</option></select></label><label>Storage<select name="storage"><option>Chilled</option><option>Frozen</option><option>Ambient</option><option>Hot holding</option></select></label><label>Prepared by<input name="preparedBy" value="${esc(who())}" required></label><label class="full">Allergens<input name="allergens"></label><label class="full">Batch / notes<input name="batch"></label><button class="btn full" type="submit">Save label</button></form></div><div class="card"><h2>Label register</h2><p>This spreadsheet gives a searchable record of what was labelled, when, by whom and with which use-by date.</p></div></div><div class="card mt"><h2>Label spreadsheet</h2>${sheet('labelSheet',cols,records,'food-labels.csv')}</div>`);
    document.getElementById('solidLabelForm').onsubmit=async e=>{e.preventDefault();arr('labels').push({id:uid(),...Object.fromEntries(new FormData(e.target)),createdAt:now(),createdBy:who()});await persist('Label saved');labelsView();};wireSheet('labelSheet',cols,records,'food-labels.csv');
  }

  styles();
  VIEWS.pestcontrol=pestView;
  VIEWS.haccp=haccpView;
  VIEWS.cleaning=cleaningView;
  VIEWS.dailychecks=dailyChecksView;
  VIEWS.waste=wasteView;
  VIEWS.traceability=traceabilityView;
  VIEWS.incidents=incidentsView;
  VIEWS.suppliers=suppliersView;
  VIEWS.probe=probeView;
  VIEWS.labels=labelsView;

  window.__solidTabForms={pestView,haccpView,cleaningView,dailyChecksView,wasteView,traceabilityView,incidentsView,suppliersView,probeView,labelsView,downloadCsv};
}
boot();
})();